name: CI/CD Packaging and Release

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, main ]

jobs:
  build_and_pack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential rpm

      - name: Configure CMake
        run: cmake -Hhomework -B_build -DBUILD_TESTS=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build Project
        run: cmake --build _build

      - name: Generate Packages (Only on Tag Push)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd _build
          cpack -G TGZ
          cpack -G ZIP
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            cpack -G DEB
            cpack -G RPM
          fi
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            cpack -G DragNDrop
          fi

      - name: Upload Binary Packages to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _build/*.tar.gz
            _build/*.zip
            _build/*.deb
            _build/*.rpm
            _build/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
